---
kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: ceph-osd
  namespace: ceph
  labels:
    app: ceph
    daemon: osd
spec:
  template:
    metadata:
      labels:
        app: ceph
        daemon: osd
      annotations:
        pod.alpha.kubernetes.io/init-containers: '[
          {
            "name": "osd-pod-init",
            "image": "docker.io/port/ceph-daemon:latest",
            "imagePullPolicy": "Always",
            "volumeMounts": [
              {
                "name": "devices",
                "mountPath": "/dev"
              },
              {
                "name": "ceph",
                "mountPath": "/var/lib/ceph"
              },
              {
                "name": "ceph-conf",
                "mountPath": "/etc/ceph"
              },
              {
                "name": "ceph-bootstrap-osd-keyring",
                "mountPath": "/var/lib/ceph/bootstrap-osd"
              },
              {
                "name": "ceph-bootstrap-mds-keyring",
                "mountPath": "/var/lib/ceph/bootstrap-mds"
              },
              {
                "name": "ceph-bootstrap-rgw-keyring",
                "mountPath": "/var/lib/ceph/bootstrap-rgw"
              },
              {
                "name": "osd-directory",
                "mountPath": "/var/lib/ceph/osd"
              }
            ],
            "securityContext": {
              "privileged": true
            },
            "env": [
              {
                "name": "CEPH_DAEMON",
                "value": "osd_directory"
              },
              {
                "name": "KV_TYPE",
                "value": "k8s"
              },
              {
                "name": "CLUSTER",
                "value": "ceph"
              },
              {
                "name": "CEPH_GET_ADMIN_KEY",
                "value": "1"
              },
              {
                "name": "INIT_ONLY",
                "value": "1"
              }
            ]
          }
        ]'
    spec:
      nodeSelector:
        node-type: storage
      containers:
        - name: osd-pod
          image: docker.io/kolla/centos-source-ceph-osd:3.0.0
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /var/log/kolla/
              name: kolla-logs
            - mountPath: /etc/localtime
              name: host-etc-localtime
              readOnly: true
            - name: devices
              mountPath: /dev
            - name: ceph
              mountPath: /var/lib/ceph
            - name: ceph-conf
              mountPath: /etc/ceph
            - name: osd-directory
              mountPath: /var/lib/ceph/osd
          securityContext:
            privileged: true
          env:
            - name: KOLLA_CONFIG_STRATEGY
              value: COPY_ONCE
          command: ["tail", "-f"]
          args:
            - /dev/null
          # livenessProbe:
          #     tcpSocket:
          #       port: 6800
          #     initialDelaySeconds: 60
          #     timeoutSeconds: 5
          # readinessProbe:
          #     tcpSocket:
          #       port: 6800
          #     timeoutSeconds: 5
          # resources:
          #   requests:
          #     memory: "512Mi"
          #     cpu: "1000m"
          #   limits:
          #     memory: "1024Mi"
          #     cpu: "2000m"
      volumes:
        - name: host-etc-localtime
          hostPath:
            path: /etc/localtime
        - name: kolla-logs
          emptyDir: {}
        - name: devices
          hostPath:
            path: /dev
        - name: ceph
          emptyDir: {}
#          hostPath:
#            path: /opt/ceph
        - name: ceph-conf
          secret:
            secretName: ceph-conf-combined
        - name: ceph-bootstrap-osd-keyring
          secret:
            secretName: ceph-bootstrap-osd-keyring
        - name: ceph-bootstrap-mds-keyring
          secret:
            secretName: ceph-bootstrap-mds-keyring
        - name: ceph-bootstrap-rgw-keyring
          secret:
            secretName: ceph-bootstrap-rgw-keyring
        - name: osd-directory
          emptyDir: {}
#          hostPath:
#            path: /home/core/data/ceph/osd
